### ISSUE TITLE
Skipping levels keeps the indentation as they weren't skipped

### ISSUE THREAD

**Issue by ifraixedes** [ycd/toc#10]
When you generate a ToC skipping a level the generated ToC keeps the indentation for the bullet as the skipped headers would be there producing a wrong rendering in GH.

Example
---

Original Markdown file (_example.md_):

```md
# Header 1

<!-- toc -->

## Header 2.1

## Header 2.2

### Header 2.2.3.1

### Header 2.2.3.2

```

Result of executing `toc -p example.md`:

```md
# Header 1

<!-- toc -->
- [Header 1](#header-1)
    * [Header 2.1](#header-21)
    * [Header 2.2](#header-22)
        * [Header 2.2.3.1](#header-2231)
        * [Header 2.2.3.2](#header-2232)

<!-- tocstop -->

## Header 2.1

## Header 2.2

### Header 2.2.3.1

### Header 2.2.3.2

```

It's rendered as
![image](https://user-images.githubusercontent.com/1731633/117245618-6a05ca80-ae3b-11eb-965a-d6805741902b.png)

Result of executing `toc -p example.md -s 1`:

```md
# Header 1

<!-- toc -->
    * [Header 2.1](#header-21)
    * [Header 2.2](#header-22)
        * [Header 2.2.3.1](#header-2231)
        * [Header 2.2.3.2](#header-2232)

<!-- tocstop -->

## Header 2.1

## Header 2.2

### Header 2.2.3.1

### Header 2.2.3.2
```

It's rendered as 
![image](https://user-images.githubusercontent.com/1731633/117245711-8e61a700-ae3b-11eb-83c2-8049e89a70e2.png)

**Comment by ycd** [comment]
Hey @ifraixedes, thanks for the detailed report, i fixed this and it is available in latest release.

**Comment by ifraixedes** [comment]
@ycd thank you for the quick response and fix.

I've given it a try and, unfortunately, it's still not working as expected.

Using the `v0.3.0` and executing `toc -p example.md -s 1` I'm getting:

```md
# Header 1

<!-- toc -->
- [Header 2.1](#header-21)
    * [Header 2.2](#header-22)
        * [Header 2.2.3.1](#header-2231)
        * [Header 2.2.3.2](#header-2232)

<!-- tocstop -->

## Header 2.1

## Header 2.2

### Header 2.2.3.1

### Header 2.2.3.2
```

Which renders as

![image](https://user-images.githubusercontent.com/1731633/117784240-9fe3ee00-b243-11eb-9cf5-6ed5ba17e833.png)


As you can see, the `Header 2.2` shouldn't be indented because it's not a child of the `Header 2.1`.

**Comment by ycd** [comment]
@ifraixedes ups, my bad! 

I misunderstood the issue completely, i'm going to fix this in a few days(needs whole lot refactor on the current logic).

**Comment by ycd** [comment]
This issue is resolved by @jceb in #14.
